Charm fixes (#438)
* Set db_name by default in charm configuration

I mistakenly took this out after initial testing, believing that the
default behaviour would be sufficient, but in fact both layer:ols-pg and
our own code rely on it being set.

* Fix quote_identifier to return text, not bytes

I misread the code in the PostgreSQL charm that I borrowed this from.
Without this, deployment fails with:

  TypeError: a bytes-like object is required, not 'str'